# Generated by Django 4.2.6 on 2023-10-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0005_users_alter_grade_course_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
